config/routes.rb
Rails.application.routes.draw do
  	

  

	resources :orders 
  	resources :products
  	resources :order_products
	resources :clients



  	
  	root 'orders#index'

	get 'test', to: 'tasks#test'

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :orders	
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_products, dependent: :destroy
	belongs_to :client

	accepts_nested_attributes_for :order_products, allow_destroy: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
	belongs_to :product , optional: true 
	belongs_to :order 	, optional: true	
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :order_products 
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
  	@clients = Client.all
  	@client = Client.new
  end


  def test
  	debug
  end

  def create
  	@client = Client.create!(client_params)
  	@client.save
  	redirect_to clients_path
  end

  def destroy
  	@client = Client.find(params[:id])
  	@client.destroy
  	redirect_to root_url
  end

  def client_params
 	 params.require(:client).permit(:name, :age)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @order_products = OrderProduct.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order_product = OrderProduct.all
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:client_id, order_products_attributes: [:id, :quantity, :product_id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  helper_method :get_cost
  def index
  	@products = Product.all
  end

  def test
  	debug
  end

   def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def update
    if @product.update(product_params)
      redirect_to root_path, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def new
    @product = Product.new
    @order_products = @product.order_products.build 
  end


  def edit
    @order_products = @product.order_products
  end

  def destroy
  	@product.destroy
  	redirect_to products_url
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
 	 params.require(:product).permit(:title, :price, order_products_attributes: [:id, :quantity] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper 
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/clients/_clients.html.erb
<%= form_for @client, html: {class: 'form-horizontal'} do |f| %>
  <div class="form-group ">
    <%= f.label :Name %><br />
    <%= f.text_field :name %> <br>
  </div>
  <div class="form-group ">
  	<%= f.label :Age %><br />
  	<%= f.number_field :age %>
  </div>

  <div class="form-group ">
  	<%= f.submit "Add", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/clients/_form.html.erb
<%= form_for @client, html: {class: 'form-horizontal'} do |f| %>
<div class="form-group ">
  	<%= f.text_field :name %> <br>
  </div>
  <div class="form-group ">
  	<%= f.text_field :age %>
  </div>
  <div class="form-group ">
  	<%= f.submit "Add", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/clients/index.html.erb
<div class="container">
	<h1>All Clients</h1>
	<div class="form">
		<h3>Fill my  form</h3>
		<%= render 'clients' %>
	</div>


	<table class="table table-striped table-inverse ">

	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Age</th>
	      <th>Action</th>
	    </tr>
	  </thead>
	 
	    <tbody>
			<% @clients.each do |c| %>
	    		<tr>	
					<td><%= c.name %></td> 		
					<td><%= c.age %></td> 	
					<td><%= link_to 'Delete', client_path(c),
				           	  method: :delete, class: "btn btn-danger",
				            	 data: {confirm: 'Do you want to remove this Client?'} %> 	
				    </td>	             	 	
				</tr>
			<% end %>
		</tbody>		
	</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsJs</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
         <%= link_to "Orders", root_path, class: "navbar-brand"  %>    
    </div>

    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        </li>
        <li> <%= link_to 'Product', products_path, class: "navbar-brand"%> </li>
      </ul>
        <%= link_to 'Clients', clients_path, class: "navbar-brand" %>
      </div>
    </div>
  </nav>
     

      </div>
    </div>
      <%= yield %>
  </body>
</html>
  

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
      <%= f.label :client %><br />
      <%= f.collection_select :client_id, Client.all, :id, :name %>
    </div>

    <%= f.fields_for :order_products do |builder| %>
      <%= render 'order_product_fields', f: builder %>
    <% end %>
      <div class="add_order_product">
       <%= link_to_add_fields "Add Order Product",  f, :order_products %>
      </div>   
  <div class="actions">
    <%= f.submit class: 'button button-default' %>
  </div>
<% end %>

app/views/orders/_order_product_fields.html.erb
<fieldset>
  <div class="form-group">	
	  <%= f.label :title, "Product" %><br />
	  <%= f.collection_select :product_id, Product.all, :id, :title %><br>
  </div>	
  <div class="form-group">		
	  <%= f.label :Quantity  %> <br>
	  <%= f.number_field :quantity %>
   		<%= link_to "remove", '#', class: "remove_fields" %>
  </div>

   
</fieldset>

app/views/orders/edit.html.erb
<div class="container">
	<h1>Editing Order</h1>
	<div class="form">
		<%= render 'form', order: @order %>
	<%= link_to 'Show', @order %> |
	<%= link_to 'Back', orders_path %>
	</div>
</div>

app/views/orders/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Orders</h1>
      <%= link_to 'New Order', new_order_path, class: "btn btn-primary" %>
  <div class="wraper">
    <main class="clearfix">
      <section class="col_01">
        <table class="table table-striped table-inverse  first_table">
          <thead>
            <tr>
              <th>Order ID</th>
              <th> Product</th>
              <th> Price</th>
              <th>Quantity</th>
         
            
            </tr>
          </thead>

          <tbody>

              <%  @order_products.map do |op| %>
              <tr>
                <td> <%= op.order.client_id %> </td>
                <td> <%= op.product.title %> </td>
                <td> <%= number_to_currency(op.product.price, :unit => "$") %> </td>
                <td> <%= op.quantity %> </td>
              </tr>
               
                <% end %>
              <% end %>
              

          </tbody>
        </table>
      </section>
        <!-- table for name -->
      <aside class="col_02">
        <table class="table table-striped table-inverse second_table">
          <tbody>
            <thead>
              <tr>
                <th>Client</th>
              </tr>

            </thead>
              <% @orders.each do |order| %>
                <tr>
                  <td><%= order.client.name %></td>
                  <td><%= link_to 'Show', order %></td>
                  <td><%= link_to 'Edit', edit_order_path(order) %></td>
                  <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
          </tbody>
        </table>      
      </aside>  
  </main>
  </div>
</div>

app/views/orders/new.html.erb
<div class="container">
	<h1>New Order</h1>
<div class="fom">
	<%= render 'form', order: @order %>
</div>
	<%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @order.client_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_product.html.erb
<%= form_for @product, html: {class: 'form-horizontal'} do |f| %>
    
   

    <div class="form-group ">
      <%= f.label :Product %><br />
      <%= f.text_field :title %> <br>
    </div>


    <div class="form-group ">
      <%= f.label :price %><br />
      <%= f.number_field :price, :placeholder => "0.00", label: false %>
    </div>


    <div class="form-group ">
    	<%= f.submit "Add", class: "btn btn-primary" %>
      | <%= link_to 'back', root_path , class: 'btn btn-default' %>

    </div>

<% end %>

app/views/products/edit.html.erb
<div class="container">
	<div class="form">
		<%= render "product" %>
	</div>
</div>

app/views/products/index.html.erb
<div class="container">
	<h1>Products</h1>
	<div class="form">
		<h3></h3>
		<%= link_to 'New', new_product_path, class: 'btn btn-success' %>	
	</div>


	<table class="table table-striped table-inverse ">

	  <thead>
	    <tr>
	      <th>Title</th>
	      <th>Price</th>
	      <th>Action</th>
	    </tr>
	  </thead>
	 	 
	    <tbody>	
			
				<% @products.each do |p| %>
	    		<tr>
					<td><%= p.title %></td>	
					<td><%= number_to_currency(p.price, :unit => "$") %></td> 
					<td><%= %></td>
					<td><%= link_to 'Edit', edit_product_path(p), class: 'btn btn-primary' %>	
					| <%= link_to 'Delete', product_path(p),
				           	  method: :delete, class: "btn btn-danger",
				            	 data: {confirm: 'Do you want to remove this Product?'} %> 	
				    </td>	             	 	
				</tr>
			<% end %>
		</tbody>		
	</table>

</div>

app/views/products/new.html.erb
<div class="container">
	<div class="form">
		<%= render "product" %>
	</div>
</div>